### ISSUE TITLE
Composer update removes bower-asset libraries

### ISSUE THREAD

**Issue by cluwong** [code-on-yii/yii2-at-least-validator#19]
The following were removed from the latest update, after running composer update:
- bower-asset/jquery
 - bower-asset/inputmask
 - bower-asset/punycode
 - bower-asset/yii2-pjax

If I remove codeonyii/yii2-at-least-validator from my project's composer.json, these 4 libs are installed. 

Could this be affected by the 'replace' section added to composer.json?

**Comment by sdlins** [comment]
Hi @cluwong. Thank you for your report. I was not sure if it could happen since I thought the "replace" would affect just the own extension, not the app using it. But, it seems it is being the problem. I will revert that change and look for another way to go ahead without the collisions I had had.

**Comment by sdlins** [comment]
@cluwong the problem you reported should be resolved now (and the orignal problem that makes me takes this wrong decision too! :+1: ) . Please, get the last release 1.2.4.

**Comment by cluwong** [comment]
It's working! Thanks for the prompt fix.

**Comment by sdlins** [comment]
You are welcome ! :+1:
